### PR TITLE
Adding support for rank cython in Windows, fixing pytorch deprecation warnings

### PR DESCRIPTION
**Pull request by lablabla**
Following suggestion here
https://github.com/pyansys/pymapdl/issues/14#issuecomment-634493921
I got the cython to run on Windows and checked on Linux as well

Tested on Windows 64bit & Ubuntu 18.04

### CODE REVIEW

**Comment by KaiyangZhou** [comment]
Thanks so much for fixing this long-standing issue for Windows users!

One more step to go: can you please test the performance of resnet50 (you can download the weights here https://kaiyangzhou.github.io/deep-person-reid/MODEL_ZOO.html) on Market1501/DukeMTMC-reID using both the evaluation codes before and after the changes? I'd like to see whether the calculation precision will be affected.

**Comment by lablabla** [comment]
I might be doing something wrong but I can't load the pretrained weights
I'm running this
```
python scripts/main.py --config-file configs/im_r50_softmax_256x128_amsgrad.yaml model.load_weights /home/devel/Downloads/resnet50_fc512_market_xent.pth.tar test.evaluate True
```
I've downloaded `resnet50_fc512_market_xent.pth.tar` from https://mega.nz/file/EaZjhKyS#lBvD3vAJ4DOmElZkNa7gyPM1RE661GUd2v9kK84gSZE

and I'm getting 
```
Traceback (most recent call last):
  File "/home/devel/dev/deep-person-reid/torchreid/utils/torchtools.py", line 84, in load_checkpoint
    checkpoint = torch.load(fpath, map_location=map_location)
  File "/home/devel/.conda/envs/torchreid/lib/python3.7/site-packages/torch/serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/devel/.conda/envs/torchreid/lib/python3.7/site-packages/torch/serialization.py", line 774, in _legacy_load
    result = unpickler.load()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x98 in position 0: invalid start byte
```

Getting the same error when using the `im_r50fc512_softmax_256x128_amsgrad.yaml` config file
This is happening in the both version, before and after the change. looking for solution, probably not running it correctly

**Comment by KaiyangZhou** [comment]
I also met the UnicodeDecodeError when using resnet50. Hmm, that's weird.

Maybe try osnet, which works for me
```
python scripts/main.py \
--config-file configs/im_osnet_x1_0_softmax_256x128_amsgrad_cosine.yaml \
--root PATH_TO_DATA \
model.load_weights saved-models/osnet/osnet_x1_0_market_256x128_amsgrad_ep150_stp60_lr0.0015_b64_fb10_softmax_labelsmooth_flip.pth \
test.evaluate True
```

**Comment by lablabla** [comment]
This one worked. please see the attached logs. Only difference (aside from the version) is the Speed, 0.0634 sec/batch vs 0.0638 sec/batch, which I guess is negligible

[1.3.4.log](https://github.com/KaiyangZhou/deep-person-reid/files/5950406/1.3.4.log)
[1.3.5.log](https://github.com/KaiyangZhou/deep-person-reid/files/5950405/1.3.5.log)

**Comment by KaiyangZhou** [comment]
Great!

The speed isn't really an issue because you normally get different speeds in different runs.

I'll merge this code with the master branch.

Thanks!

**Pull request merged**
